# Generated by Django 2.0.2 on 2018-04-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_auto_20180416_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='period',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='time',
            name='week',
            field=models.IntegerField(),
        ),
    ]
