# Generated by Django 2.0.2 on 2018-05-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_auto_20180417_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
        migrations.AddField(
            model_name='course',
            name='class_rome',
            field=models.CharField(default='0000', max_length=6),
        ),
        migrations.AddField(
            model_name='course',
            name='compulsory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='credit',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='course',
            name='popular',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='popular_limit',
            field=models.CharField(default=60, max_length=10),
        ),
    ]
