# Generated by Django 2.0.2 on 2018-05-05 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_auto_20180501_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='class_rome',
            new_name='class_room',
        ),
    ]
