# Generated by Django 2.0.2 on 2018-05-05 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_auto_20180505_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='class_room',
            new_name='classroom',
        ),
    ]
