# Generated by Django 2.0.2 on 2018-05-08 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_auto_20180505_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='time',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.Teacher'),
        ),
        migrations.AddField(
            model_name='coursetime',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.Course'),
        ),
        migrations.AddField(
            model_name='coursetime',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.Time'),
        ),
        migrations.AlterUniqueTogether(
            name='coursetime',
            unique_together={('course', 'time')},
        ),
    ]
